# PotatoCreator class
# Reads data from the potato dataset using the CSVReader class
# Uses a random index to grab a random row from the dataset
# Creates and returns a new PotatoDetail object 

# Author: Ash-Lee Hommy 040840815
# Nov 1st, 2017
require_relative 'CSVReader'
require_relative 'PotatoDetail'

class PotatoCreator
  
  # Potato object with autogenerated getters and setters
  # Type: PotatoDetail
  attr_accessor :potato
  
  # create_potato method
  # Reads data from the dataset and creates an array of arrays
  # Uses a random index to choose a random row from the data
  # Returns a PotatoDetail object with all random attributes set
  def create_potato
    # random index to pull a row from the CSV
    index = random_index
    
    # a CSVReader returns the data set as an array
    # use one random row to create a Potato
    reader = CSVReader.new
    potato_arr = reader.read_file
    
    # represents one random row of data
    potato_row = potato_arr[index]
    
    # Useful data in the dataset:
    # [0] - Year
    # [1] - Province
    # [4] - Coordinate
    # [5] - Value 
    year = potato_row[0].to_i
    province = potato_row[1]
    coord = potato_row[4].to_i
    value = potato_row[5].to_i
    
    # set the Potato Body: year % number of bodies
    # set the Eyes: coord % number of eyes
    # set the Mouth: value % number of mouths
    body = year % 6
    eyes = coord % 4
    mouth = value % 4
    
    #return a new PotatoDetail object with attributes set
    @potato = PotatoDetail.new(body, eyes, mouth)
    
  end
  
  # Private helper method random_index
  # return a random int to be used to grab a random line 
  # from the CSV file (between 0 and 6484)
  # Row 0 is the column names! 
  private
    def random_index
      rand(0..6484)
    end
  
end

